<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>passwordField</name>
   <tag></tag>
   <elementGuidId>bfa06897-df34-4ed2-b629-335f369dd1c2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>//android.view.View[@content-desc=&quot;Masukkan alamat email dan kata sandi Anda untuk mulai menggunakan layanan kami!
Email/Username
Password&quot;]/android.widget.ImageView[3]</locator>
   <locatorCollection>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>[{&quot;key&quot;:&quot;elementId&quot;,&quot;value&quot;:null,&quot;name&quot;:&quot;elementId&quot;},{&quot;key&quot;:&quot;index&quot;,&quot;value&quot;:&quot;2&quot;,&quot;name&quot;:&quot;index&quot;},{&quot;key&quot;:&quot;package&quot;,&quot;value&quot;:&quot;id.zicare.rsudmrhpthapps.dev&quot;,&quot;name&quot;:&quot;package&quot;},{&quot;key&quot;:&quot;class&quot;,&quot;value&quot;:&quot;android.widget.ImageView&quot;,&quot;name&quot;:&quot;class&quot;},{&quot;key&quot;:&quot;text&quot;,&quot;value&quot;:&quot;&quot;,&quot;name&quot;:&quot;text&quot;},{&quot;key&quot;:&quot;resource-id&quot;,&quot;value&quot;:&quot;&quot;,&quot;name&quot;:&quot;resource-id&quot;},{&quot;key&quot;:&quot;checkable&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;checkable&quot;},{&quot;key&quot;:&quot;checked&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;checked&quot;},{&quot;key&quot;:&quot;clickable&quot;,&quot;value&quot;:&quot;true&quot;,&quot;name&quot;:&quot;clickable&quot;},{&quot;key&quot;:&quot;enabled&quot;,&quot;value&quot;:&quot;true&quot;,&quot;name&quot;:&quot;enabled&quot;},{&quot;key&quot;:&quot;focusable&quot;,&quot;value&quot;:&quot;true&quot;,&quot;name&quot;:&quot;focusable&quot;},{&quot;key&quot;:&quot;focused&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;focused&quot;},{&quot;key&quot;:&quot;long-clickable&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;long-clickable&quot;},{&quot;key&quot;:&quot;password&quot;,&quot;value&quot;:&quot;true&quot;,&quot;name&quot;:&quot;password&quot;},{&quot;key&quot;:&quot;scrollable&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;scrollable&quot;},{&quot;key&quot;:&quot;selected&quot;,&quot;value&quot;:&quot;false&quot;,&quot;name&quot;:&quot;selected&quot;},{&quot;key&quot;:&quot;bounds&quot;,&quot;value&quot;:&quot;[54,1384][1026,1516]&quot;,&quot;name&quot;:&quot;bounds&quot;},{&quot;key&quot;:&quot;displayed&quot;,&quot;value&quot;:&quot;true&quot;,&quot;name&quot;:&quot;displayed&quot;},{&quot;key&quot;:&quot;hint&quot;,&quot;value&quot;:&quot;Masukkan kata sandi/password&quot;,&quot;name&quot;:&quot;hint&quot;}]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.widget.ImageView&quot;).instance(2)</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//android.view.View[@content-desc=&quot;Masukkan alamat email dan kata sandi Anda untuk mulai menggunakan layanan kami!
Email/Username
Password&quot;]/android.widget.ImageView[3]</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>android.widget.ImageView</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
